### ISSUE TITLE
greeting of undefined?

### ISSUE THREAD

**Issue by naxmefy** [albatrocity/Boiled-Brunch-with-Chaplin#2]
```
$ bicofun npm start

> brunch-chaplin-auth-app-boilerplate@0.0.1 start C:\Users\naxmeify\Documents\BitBucket\bicofun
> brunch watch --server

03 Apr 12:54:08 - info: application started on http://localhost:3333/
03 Apr 12:54:08 - error: Compiling of 'app\views\home\templates\home.jade' failed. app\views\home\templates\home.jade:5
    3| = jade.helpers.greeting("Visitor")
    4| if jade.helpers.loggedIn()
  > 5|   h2 You're a great user.

Cannot call method 'greeting' of undefined
```

Steps i did:
1. downloaded
2. npm install
3. bower install
4. npm start

**Comment by albatrocity** [comment]
@Naxmeify whoops, sorry man. Try locking the version of `jade-brunch` in your package.json file to `"jade-brunch": "1.8.0"`

The 1.8.1 release [updated how you can globally pass things to jade](https://github.com/brunch/jade-brunch/blob/master/CHANGELOG.md#jade-brunch-181-26-february-2014), and I haven't worked through how to achieve the current functionality with that release.

Let me know if that fixes the issue.

**Comment by albatrocity** [comment]
Also, I'm not sure if I have this documented anywhere, but those functions that are namsepaced under `jade.helpers` are located in [app/lib/view-helper.coffee](https://github.com/albatrocity/Boiled-Brunch-with-Chaplin/blob/master/app/lib/view-helper.coffee)
